In [1]:
import torch
import numpy

In [2]:
# Создайте случайный FloatTensor размера 3x4x5

d= torch.FloatTensor(3, 4, 5)

In [3]:
# Выведите его форму (shape)

print(f"shape (d) - {d.shape},\n {d}")

shape (d) - torch.Size([3, 4, 5]),
 tensor([[[3.3448e+00, 4.4982e-43, 3.3448e+00, 4.4982e-43, 2.4670e+01],
         [4.4982e-43, 8.2217e+00, 4.4982e-43, 2.4696e+01, 4.4982e-43],
         [2.4696e+01, 4.4982e-43, 8.2312e+00, 4.4982e-43, 8.2312e+00],
         [4.4982e-43, 3.3448e+00, 4.4982e-43, 3.3448e+00, 4.4982e-43]],

        [[3.3448e+00, 4.4982e-43, 3.3448e+00, 4.4982e-43, 8.2317e+00],
         [4.4982e-43, 8.2317e+00, 4.4982e-43, 2.4679e+01, 4.4982e-43],
         [2.4679e+01, 4.4982e-43, 2.4661e+01, 4.4982e-43, 2.4661e+01],
         [4.4982e-43, 2.4671e+01, 4.4982e-43, 8.2656e+00, 4.4982e-43]],

        [[8.2414e+00, 4.4982e-43, 8.2414e+00, 4.4982e-43, 3.3448e+00],
         [4.4982e-43, 3.3448e+00, 4.4982e-43, 8.2768e+00, 4.4982e-43],
         [8.2768e+00, 4.4982e-43, 8.2162e+00, 4.4982e-43, 8.2162e+00],
         [4.4982e-43, 8.2276e+00, 4.4982e-43, 8.2276e+00, 4.4982e-43]]])


In [4]:
# Приведите его к форме 6 X 10

c1 = d.reshape(6,10)
print(c1.shape)
c1

torch.Size([6, 10])


tensor([[3.3448e+00, 4.4982e-43, 3.3448e+00, 4.4982e-43, 2.4670e+01, 4.4982e-43,
         8.2217e+00, 4.4982e-43, 2.4696e+01, 4.4982e-43],
        [2.4696e+01, 4.4982e-43, 8.2312e+00, 4.4982e-43, 8.2312e+00, 4.4982e-43,
         3.3448e+00, 4.4982e-43, 3.3448e+00, 4.4982e-43],
        [3.3448e+00, 4.4982e-43, 3.3448e+00, 4.4982e-43, 8.2317e+00, 4.4982e-43,
         8.2317e+00, 4.4982e-43, 2.4679e+01, 4.4982e-43],
        [2.4679e+01, 4.4982e-43, 2.4661e+01, 4.4982e-43, 2.4661e+01, 4.4982e-43,
         2.4671e+01, 4.4982e-43, 8.2656e+00, 4.4982e-43],
        [8.2414e+00, 4.4982e-43, 8.2414e+00, 4.4982e-43, 3.3448e+00, 4.4982e-43,
         3.3448e+00, 4.4982e-43, 8.2768e+00, 4.4982e-43],
        [8.2768e+00, 4.4982e-43, 8.2162e+00, 4.4982e-43, 8.2162e+00, 4.4982e-43,
         8.2276e+00, 4.4982e-43, 8.2276e+00, 4.4982e-43]])

In [11]:
# Создайте случайный IntTensor размера 10

c = torch.randperm(10)
print(c)
print(c.shape)

tensor([0, 2, 3, 8, 7, 9, 5, 1, 4, 6])
torch.Size([10])


In [14]:
# Умножьте созданный FloatTensor на созданный IntTensor поэлементно

a = c1*c
print(a)

tensor([[0.0000e+00, 8.9963e-43, 1.0034e+01, 3.5985e-42, 1.7269e+02, 4.0484e-42,
         4.1109e+01, 4.4982e-43, 9.8785e+01, 2.6989e-42],
        [0.0000e+00, 8.9963e-43, 2.4694e+01, 3.5985e-42, 5.7619e+01, 4.0484e-42,
         1.6724e+01, 4.4982e-43, 1.3379e+01, 2.6989e-42],
        [0.0000e+00, 8.9963e-43, 1.0034e+01, 3.5985e-42, 5.7622e+01, 4.0484e-42,
         4.1158e+01, 4.4982e-43, 9.8717e+01, 2.6989e-42],
        [0.0000e+00, 8.9963e-43, 7.3983e+01, 3.5985e-42, 1.7263e+02, 4.0484e-42,
         1.2335e+02, 4.4982e-43, 3.3062e+01, 2.6989e-42],
        [0.0000e+00, 8.9963e-43, 2.4724e+01, 3.5985e-42, 2.3414e+01, 4.0484e-42,
         1.6724e+01, 4.4982e-43, 3.3107e+01, 2.6989e-42],
        [0.0000e+00, 8.9963e-43, 2.4648e+01, 3.5985e-42, 5.7513e+01, 4.0484e-42,
         4.1138e+01, 4.4982e-43, 3.2911e+01, 2.6989e-42]])


In [15]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

d = a.matmul(a.t())

print(d)
print(d.shape)


tensor([[41371.8398, 12207.2705, 21495.2070, 38890.5273,  8249.4707, 15121.6191],
        [12207.2705,  4388.3818,  5576.9526, 14278.6797,  2682.2417,  5050.8013],
        [21495.2070,  5576.9526, 14859.9268, 19030.1504,  5553.8037,  8503.3242],
        [38890.5273, 14278.6797, 19030.1504, 51582.1211,  9028.5342, 17914.4062],
        [ 8249.4707,  2682.2417,  5553.8037,  9028.5342,  2535.2769,  3733.5835],
        [15121.6191,  5050.8013,  8503.3242, 17914.4062,  3733.5835,  6690.7529]])
torch.Size([6, 6])


In [16]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
import torch 
x=torch.tensor(1.0, requires_grad=True)
z= torch.tensor(0.5, requires_grad=True) 
t= torch.tensor(2.0, requires_grad=True)
y=x**3+z+75*t 
y.backward() 
x.grad 
z.grad
t.grad
print(x.grad, z.grad, t.grad)

tensor(3.) tensor(1.) tensor(75.)


In [17]:
# Создайте единичный тензор размера 5x6

o = torch.eye(5, 6)
o

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.]])

In [18]:
# Переведите его в формат numpy
b = o.numpy()
b

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]], dtype=float32)

In [19]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 
from torch.autograd import Variable
def function(x, w1):
    return x**w1 - 2 * x**2 + 5

def gradient(x):
    return torch.autograd.grad(function(x, w1), x)[0]

w1 = 3
x = Variable(torch.Tensor([2]), requires_grad=True)
learning_rate = 0.01
num_iterations = 100
for i in range(num_iterations):
    x_grad = gradient(x)
    x.data -= learning_rate * x_grad
    if not i%5:
        print(f"Iteration {i+1}, x = {x.data[0]:.2f}, y = {function(x.data[0], w1):.2f}")

Iteration 1, x = 1.96, y = 4.85
Iteration 6, x = 1.80, y = 4.36
Iteration 11, x = 1.69, y = 4.12
Iteration 16, x = 1.61, y = 3.99
Iteration 21, x = 1.55, y = 3.92
Iteration 26, x = 1.50, y = 3.88
Iteration 31, x = 1.47, y = 3.85
Iteration 36, x = 1.44, y = 3.84
Iteration 41, x = 1.42, y = 3.83
Iteration 46, x = 1.40, y = 3.83
Iteration 51, x = 1.39, y = 3.82
Iteration 56, x = 1.38, y = 3.82
Iteration 61, x = 1.37, y = 3.82
Iteration 66, x = 1.36, y = 3.82
Iteration 71, x = 1.36, y = 3.82
Iteration 76, x = 1.35, y = 3.82
Iteration 81, x = 1.35, y = 3.82
Iteration 86, x = 1.35, y = 3.82
Iteration 91, x = 1.34, y = 3.82
Iteration 96, x = 1.34, y = 3.81
