In [1]:
import torch
import numpy

In [2]:
# Создайте случайный FloatTensor размера 3x4x5

d= torch.FloatTensor(3, 4, 5)

In [4]:
# Выведите его форму (shape)

print(f"shape (d) - {d.shape},\n {d}")

shape (d) - torch.Size([3, 4, 5]),
 tensor([[[8.8283e-04, 6.5020e-43, 8.8283e-04, 6.5020e-43, 8.5241e-04],
         [6.5020e-43, 8.5241e-04, 6.5020e-43, 5.7638e-06, 6.5020e-43],
         [5.7638e-06, 6.5020e-43, 5.7638e-06, 6.5020e-43, 5.7638e-06],
         [6.5020e-43, 5.7638e-06, 6.5020e-43, 5.7638e-06, 6.5020e-43]],

        [[5.7638e-06, 6.5020e-43, 5.7638e-06, 6.5020e-43, 8.6960e-04],
         [6.5020e-43, 8.6974e-04, 6.5020e-43, 8.8430e-04, 6.5020e-43],
         [8.8430e-04, 6.5020e-43, 5.7638e-06, 6.5020e-43, 5.7638e-06],
         [6.5020e-43, 8.8448e-04, 6.5020e-43, 8.8448e-04, 6.5020e-43]],

        [[8.5229e-04, 6.5020e-43, 8.5229e-04, 6.5020e-43, 8.6813e-04],
         [6.5020e-43, 8.6813e-04, 6.5020e-43, 8.8330e-04, 6.5020e-43],
         [8.8215e-04, 6.5020e-43, 5.7638e-06, 6.5020e-43, 5.7638e-06],
         [6.5020e-43, 8.6822e-04, 6.5020e-43, 8.6822e-04, 6.5020e-43]]])


In [17]:
# Приведите его к форме 6 X 10

c1 = d.reshape(6,10)
print(c1.shape)
c1

torch.Size([6, 10])


tensor([[8.8283e-04, 6.5020e-43, 8.8283e-04, 6.5020e-43, 8.5241e-04, 6.5020e-43,
         8.5241e-04, 6.5020e-43, 5.7638e-06, 6.5020e-43],
        [5.7638e-06, 6.5020e-43, 5.7638e-06, 6.5020e-43, 5.7638e-06, 6.5020e-43,
         5.7638e-06, 6.5020e-43, 5.7638e-06, 6.5020e-43],
        [5.7638e-06, 6.5020e-43, 5.7638e-06, 6.5020e-43, 8.6960e-04, 6.5020e-43,
         8.6974e-04, 6.5020e-43, 8.8430e-04, 6.5020e-43],
        [8.8430e-04, 6.5020e-43, 5.7638e-06, 6.5020e-43, 5.7638e-06, 6.5020e-43,
         8.8448e-04, 6.5020e-43, 8.8448e-04, 6.5020e-43],
        [8.5229e-04, 6.5020e-43, 8.5229e-04, 6.5020e-43, 8.6813e-04, 6.5020e-43,
         8.6813e-04, 6.5020e-43, 8.8330e-04, 6.5020e-43],
        [8.8215e-04, 6.5020e-43, 5.7638e-06, 6.5020e-43, 5.7638e-06, 6.5020e-43,
         8.6822e-04, 6.5020e-43, 8.6822e-04, 6.5020e-43]])

In [26]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
a1= torch.FloatTensor([1, 4, 2, 2, 1, 1, 4, 2, 2, 1])
a = c1*a1
print(a)

tensor([[8.8283e-04, 2.6008e-42, 1.7657e-03, 1.3004e-42, 8.5241e-04, 6.5020e-43,
         3.4097e-03, 1.3004e-42, 1.1528e-05, 6.5020e-43],
        [5.7638e-06, 2.6008e-42, 1.1528e-05, 1.3004e-42, 5.7638e-06, 6.5020e-43,
         2.3055e-05, 1.3004e-42, 1.1528e-05, 6.5020e-43],
        [5.7638e-06, 2.6008e-42, 1.1528e-05, 1.3004e-42, 8.6960e-04, 6.5020e-43,
         3.4790e-03, 1.3004e-42, 1.7686e-03, 6.5020e-43],
        [8.8430e-04, 2.6008e-42, 1.1528e-05, 1.3004e-42, 5.7638e-06, 6.5020e-43,
         3.5379e-03, 1.3004e-42, 1.7690e-03, 6.5020e-43],
        [8.5229e-04, 2.6008e-42, 1.7046e-03, 1.3004e-42, 8.6813e-04, 6.5020e-43,
         3.4725e-03, 1.3004e-42, 1.7666e-03, 6.5020e-43],
        [8.8215e-04, 2.6008e-42, 1.1528e-05, 1.3004e-42, 5.7638e-06, 6.5020e-43,
         3.4729e-03, 1.3004e-42, 1.7364e-03, 6.5020e-43]])


In [27]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

d = a.matmul(a.t())

print(d)
print(d.shape)


tensor([[1.6249e-05, 1.0910e-07, 1.2649e-05, 1.2889e-05, 1.6363e-05, 1.2665e-05],
        [1.0910e-07, 8.6376e-10, 1.0577e-07, 1.0722e-07, 1.2999e-07, 1.0534e-07],
        [1.2649e-05, 1.0577e-07, 1.5988e-05, 1.5447e-05, 1.5985e-05, 1.5163e-05],
        [1.2889e-05, 1.0722e-07, 1.5447e-05, 1.6428e-05, 1.6189e-05, 1.6139e-05],
        [1.6363e-05, 1.2999e-07, 1.5985e-05, 1.6189e-05, 1.9565e-05, 1.5904e-05],
        [1.2665e-05, 1.0534e-07, 1.5163e-05, 1.6139e-05, 1.5904e-05, 1.5855e-05]])
torch.Size([6, 6])


In [28]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
import torch 
x=torch.tensor(1.0, requires_grad=True)
z= torch.tensor(0.5, requires_grad=True) 
t= torch.tensor(2.0, requires_grad=True)
y=x**3+z+75*t 
y.backward() 
x.grad 
z.grad
t.grad
print(x.grad, z.grad, t.grad)

tensor(3.) tensor(1.) tensor(75.)


In [30]:
# Создайте единичный тензор размера 5x6

o = torch.eye(5, 6)
o

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.]])

In [31]:
# Переведите его в формат numpy
b = o.numpy()
b

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]], dtype=float32)

In [42]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 
from torch.autograd import Variable
def function(x, w1):
    return x**w1 - 2 * x**2 + 5

def gradient(x):
    return torch.autograd.grad(function(x, w1), x)[0]

w1 = 3
x = Variable(torch.Tensor([2]), requires_grad=True)
learning_rate = 0.01
num_iterations = 100
for i in range(num_iterations):
    x_grad = gradient(x)
    x.data -= learning_rate * x_grad
    if not i%5:
        print(f"Iteration {i+1}, x = {x.data[0]:.2f}, y = {function(x.data[0], w1):.2f}")

Iteration 1, x = 1.96, y = 4.85
Iteration 6, x = 1.80, y = 4.36
Iteration 11, x = 1.69, y = 4.12
Iteration 16, x = 1.61, y = 3.99
Iteration 21, x = 1.55, y = 3.92
Iteration 26, x = 1.50, y = 3.88
Iteration 31, x = 1.47, y = 3.85
Iteration 36, x = 1.44, y = 3.84
Iteration 41, x = 1.42, y = 3.83
Iteration 46, x = 1.40, y = 3.83
Iteration 51, x = 1.39, y = 3.82
Iteration 56, x = 1.38, y = 3.82
Iteration 61, x = 1.37, y = 3.82
Iteration 66, x = 1.36, y = 3.82
Iteration 71, x = 1.36, y = 3.82
Iteration 76, x = 1.35, y = 3.82
Iteration 81, x = 1.35, y = 3.82
Iteration 86, x = 1.35, y = 3.82
Iteration 91, x = 1.34, y = 3.82
Iteration 96, x = 1.34, y = 3.81
